{
    "openapi": "3.0.0",
    "info": {
      "title": "Backend-capstone",
      "contact": {},
      "version": "1.3"
    },
    "servers": [
        {
          "url": "https://be-capstone-project-aethyk4pbq-et.a.run.app",
          "description": "Backend API Server cpastone Quisiin",
          "variables": {}
        }
    ],
    "paths": {
      "/users/profile": {
        "get": {
          "tags": [
            "Protected"
          ],
          "summary": "get user profile",
          "operationId": "getuserprofile",
          "parameters": [],
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false,
          "security": [
            {
              "bearer": []
            }
          ]
        }
      },
      "/users/profile/history": {
        "get": {
          "tags": [
            "Protected"
          ],
          "summary": "get user kuesioner history",
          "operationId": "getuserkuesionerhistory",
          "parameters": [],
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false,
          "security": [
            {
              "bearer": []
            }
          ]
        }
      },
      "/users/profile/kuesioner": {
        "get": {
          "tags": [
            "Protected"
          ],
          "summary": "get user own kuesioners",
          "operationId": "getuserownkuesioners",
          "parameters": [],
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false,
          "security": [
            {
              "bearer": []
            }
          ]
        }
      },
      "/users/kuesioner/13/answers": {
        "get": {
          "tags": [
            "Protected"
          ],
          "summary": "get user kuesioner history Copy",
          "operationId": "getuserkuesionerhistoryCopy",
          "parameters": [],
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false,
          "security": [
            {
              "bearer": []
            }
          ]
        }
      },
      "/users/delete": {
        "delete": {
          "tags": [
            "Protected"
          ],
          "summary": "delete user",
          "operationId": "deleteuser",
          "parameters": [],
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false,
          "security": [
            {
              "bearer": []
            }
          ]
        }
      },
      "/users/update": {
        "put": {
          "tags": [
            "Protected"
          ],
          "summary": "update user profile",
          "operationId": "updateuserprofile",
          "parameters": [],
          "requestBody": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/updateuserprofilerequest"
                    },
                    {
                      "example": {
                        "nama": "a Doe",
                        "umur": 30,
                        "pekerjaan": "Software Engineer"
                      }
                    }
                  ]
                },
                "example": {
                  "nama": "a Doe",
                  "umur": 30,
                  "pekerjaan": "Software Engineer"
                }
              }
            },
            "required": true
          },
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false,
          "security": [
            {
              "bearer": []
            }
          ]
        }
      },
      "/users/profile/picture": {
        "post": {
          "tags": [
            "Protected"
          ],
          "summary": "update user profile picture",
          "operationId": "updateuserprofilepicture",
          "parameters": [],
          "requestBody": {
            "content": {
              "multipart/form-data": {
                "encoding": {},
                "schema": {
                  "required": [
                    "profilePicture"
                  ],
                  "type": "object",
                  "properties": {
                    "profilePicture": {
                      "type": "string",
                      "format": "binary"
                    }
                  }
                }
              }
            },
            "required": false
          },
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false,
          "security": [
            {
              "bearer": []
            }
          ]
        }
      },
      "/users/logout": {
        "post": {
          "tags": [
            "Protected"
          ],
          "summary": "logout",
          "operationId": "logout",
          "parameters": [],
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false,
          "security": [
            {
              "bearer": []
            }
          ]
        }
      },
      "/users/register": {
        "post": {
          "tags": [
            "Auth"
          ],
          "summary": "register account",
          "operationId": "registeraccount",
          "parameters": [],
          "requestBody": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/registeraccountrequest"
                    },
                    {
                      "example": {
                        "nama": "John Doe",
                        "umur": 25,
                        "gender": "laki-laki",
                        "phone": "23454421",
                        "email": "jni2@example.com",
                        "password": "password123",
                        "confirm_password": "password123"
                      }
                    }
                  ]
                },
                "example": {
                  "nama": "John Doe",
                  "umur": 25,
                  "gender": "laki-laki",
                  "phone": "23454421",
                  "email": "jni2@example.com",
                  "password": "password123",
                  "confirm_password": "password123"
                }
              }
            },
            "required": true
          },
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false
        }
      },
      "/users/login": {
        "post": {
          "tags": [
            "Auth"
          ],
          "summary": "login user",
          "operationId": "loginuser",
          "parameters": [],
          "requestBody": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/loginuserrequest"
                    },
                    {
                      "example": {
                        "email": "jni2@example.com",
                        "password": "password123"
                      }
                    }
                  ]
                },
                "example": {
                  "email": "jni2@example.com",
                  "password": "password123"
                }
              }
            },
            "required": true
          },
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false
        }
      },
      "/kategoris": {
        "get": {
          "tags": [
            "Kategori"
          ],
          "summary": "get all kategori",
          "operationId": "getallkategori",
          "parameters": [],
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false
        }

    },
      "/kategoris/1": {
        "get": {
          "tags": [
            "Kategori"
          ],
          "summary": "get specific kategori",
          "operationId": "getspecifickategori",
          "parameters": [],
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false
        }
      },
      "/kuesioners": {
        "post": {
          "tags": [
            "Kuesioners"
          ],
          "summary": "create new kuesioners",
          "operationId": "createnewkuesioners",
          "parameters": [],
          "requestBody": {
            "content": {
              "multipart/form-data": {
                "encoding": {},
                "schema": {
                  "required": [
                    "judul",
                    "deskripsi",
                    "rentang_usia",
                    "kategori_id[0]",
                    "link",
                    "image",
                    "kategori_id[1]"
                  ],
                  "type": "object",
                  "properties": {
                    "judul": {
                      "type": "string",
                      "example": "test"
                    },
                    "deskripsi": {
                      "type": "string",
                      "example": "lorem ipsum"
                    },
                    "rentang_usia": {
                      "type": "integer",
                      "format": "int32",
                      "example": 2032
                    },
                    "kategori_id[0]": {
                      "type": "integer",
                      "format": "int32",
                      "example": 1
                    },
                    "link": {
                      "type": "string",
                      "example": "https://forms.gle/ux6f2CpKdPtr4H5U9"
                    },
                    "image": {
                      "type": "string",
                      "format": "binary"
                    },
                    "kategori_id[1]": {
                      "type": "integer",
                      "format": "int32",
                      "example": 2
                    }
                  }
                }
              }
            },
            "required": false
          },
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false,
          "security": [
            {
              "bearer": []
            }
          ]
        },
        "get": {
          "tags": [
            "Kuesioners"
          ],
          "summary": "get all kuesioner data",
          "operationId": "getallkuesionerdata",
          "parameters": [],
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false
        }
      },
      "/kuesioners/13/answer": {
        "post": {
          "tags": [
            "Kuesioners"
          ],
          "summary": "user menjawab kuesioner",
          "operationId": "usermenjawabkuesioner",
          "parameters": [],
          "requestBody": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/usermenjawabkuesionerrequest"
                    },
                    {
                      "example": {
                        "answers": [
                          "Answer 1"
                        ]
                      }
                    }
                  ]
                },
                "example": {
                  "answers": [
                    "Answer 1"
                  ]
                }
              }
            },
            "required": true
          },
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false,
          "security": [
            {
              "bearer": []
            }
          ]
        }
      },
      "/kuesioners/details/13": {
        "get": {
          "tags": [
            "Kuesioners"
          ],
          "summary": "get specific kuesioner data",
          "operationId": "getspecifickuesionerdata",
          "parameters": [],
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false
        }
      }
    },
    "components": {
      "schemas": {
        "updateuserprofilerequest": {
          "title": "updateuserprofilerequest",
          "required": [
            "nama",
            "umur",
            "pekerjaan"
          ],
          "type": "object",
          "properties": {
            "nama": {
              "type": "string"
            },
            "umur": {
              "type": "integer",
              "format": "int32"
            },
            "pekerjaan": {
              "type": "string"
            }
          },
          "example": {
            "nama": "a Doe",
            "umur": 30,
            "pekerjaan": "Software Engineer"
          }
        },
        "registeraccountrequest": {
          "title": "registeraccountrequest",
          "required": [
            "nama",
            "umur",
            "gender",
            "phone",
            "email",
            "password",
            "confirm_password"
          ],
          "type": "object",
          "properties": {
            "nama": {
              "type": "string"
            },
            "umur": {
              "type": "integer",
              "format": "int32"
            },
            "gender": {
              "type": "string"
            },
            "phone": {
              "type": "string"
            },
            "email": {
              "type": "string"
            },
            "password": {
              "type": "string"
            },
            "confirm_password": {
              "type": "string"
            }
          },
          "example": {
            "nama": "John Doe",
            "umur": 25,
            "gender": "laki-laki",
            "phone": "23454421",
            "email": "jni2@example.com",
            "password": "password123",
            "confirm_password": "password123"
          }
        },
        "loginuserrequest": {
          "title": "loginuserrequest",
          "required": [
            "email",
            "password"
          ],
          "type": "object",
          "properties": {
            "email": {
              "type": "string"
            },
            "password": {
              "type": "string"
            }
          },
          "example": {
            "email": "jni2@example.com",
            "password": "password123"
          }
        },
        "usermenjawabkuesionerrequest": {
          "title": "usermenjawabkuesionerrequest",
          "required": [
            "answers"
          ],
          "type": "object",
          "properties": {
            "answers": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "description": ""
            }
          },
          "example": {
            "answers": [
              "Answer 1"
            ]
          }
        },
        "createnewcategoryrequest": {
          "title": "createnewcategoryrequest",
          "required": [
            "kategori_nama",
            "kategori_desc"
          ],
          "type": "object",
          "properties": {
            "kategori_nama": {
              "type": "string"
            },
            "kategori_desc": {
              "type": "string"
            }
          },
          "example": {
            "kategori_nama": "Category",
            "kategori_desc": "Description"
          }
        }
      },
      "securitySchemes": {
        "bearer": {
          "type": "http",
          "scheme": "bearer"
        }
      }
    },
    "security": [],
    "tags": [
      {
        "name": "Protected"
      },
      {
        "name": "Auth"
      },
      {
        "name": "Kategori"
      },
      {
        "name": "Kuesioners"
      },
      {
        "name": "testing"
      }
    ]
  }